### ISSUE TITLE
No public port '1337/tcp' published

### ISSUE THREAD

**Issue by dmalan** [cs50/ide50#1]
```
$ python3 -m ide50
8080/tcp -> 0.0.0.0:32770
8081/tcp -> 0.0.0.0:32769
8082/tcp -> 0.0.0.0:32768
Error: No public port '1337/tcp' published for d108cf6a09818664926e510e5e9fb321451c7f289c5bdedb1ee0ebf20de536a5
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/malan/ide50/ide50/__main__.py", line 188, in <module>
    main()
  File "/Users/malan/ide50/ide50/__main__.py", line 150, in main
    print(_("Running on {} (Run ide50 -S to stop)").format(f"http://{ports(container.split()[0], C9_PORT)}/"))
  File "/Users/malan/ide50/ide50/__main__.py", line 159, in ports
    return subprocess.check_output(cmd).decode().rstrip()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'port', 'd108cf6a09818664926e510e5e9fb321451c7f289c5bdedb1ee0ebf20de536a5', '1337']' returned non-zero exit status 1
```

**Comment by dmalan** [comment]
Stopping all existing containers seems to have fixed.

**Comment by dmalan** [comment]
Actually, seems to err like this if 8080, 8081, or 8082 is in use, as via `cli50` or `docker-compose`?

**Comment by kzidane** [comment]
Yeah, these ports need to be exposed in the IDE's Dockerfile for `--publish-all` to work when the previous command fails.

**Comment by kzidane** [comment]
Fixed.
